In [ ]:
import pandas as pd
df = pd.read_spss(r"C:\Users\No\Downloads\D00162\data.sav")
df.head()

,id,a1,a2,ra2,rra2,level,area,a3,a3.a,a4,...,r1,r1a,r2,r2a,r3a,r3aa,r3b,r3ba,r4,weight
0,T311139126,男,49.0,56.0,50-59歲,工商市區,中彰投之第1層,屏東縣,,是(跳答至A6),...,有全職工作,,批發及零售業,,雇主,,有,4.0,58001~77000元,0.705220
1,T124214039,男,51.0,54.0,50-59歲,工商市區,北北基宜之第2層,台北市,,是(跳答至A6),...,有全職工作,,批發及零售業,,雇主,,有,10.0,77001元以上,0.897077
2,T312242012,男,86.0,19.0,18-19歲,都會核心,中彰投之第1層,台中市,,是(跳答至A6),...,學生/進修在學且沒有工作,,NaN,,NaN,,NaN,NaN,17001元~22000元,2.101220
3,T121208023,女,48.0,57.0,50-59歲,工商市區,北北基宜之第2層,南投縣,,是(跳答至A6),...,家庭主婦且沒有工作,,NaN,,NaN,,NaN,NaN,無收入,1.013306
4,T124214002,女,46.0,59.0,50-59歲,工商市區,北北基宜之第2層,新北市,,是(跳答至A6),...,已經退休,,NaN,,NaN,,NaN,NaN,17000元以下,0.742946

In [3]:
df.shape

(2098, 646)

In [1]:
import pandas as pd
df = pd.read_spss(r"C:\Users\USER\Downloads\D00224_2\data.sav")
df.head()

,id,startdate,enddate,duration_in_seconds,q1,q2,q3,q3_other,q4,q4_88_text,...,q39_1,q40_1,q41_1,q42_1,rq21a,rq37a,qrq2,rrq2,weight,r
0,1030252,2021-06-23 23:48:22,2021-06-24 00:13:26,1503.0,女,54.0,(02)台北市,,(20)碩士,,...,快樂,65.0,65.0,維持現狀,答對,答對,56.0,50-59歲,0.349006,符合
1,1030607N,2021-07-02 17:35:01,2021-07-02 17:49:30,869.0,男,47.0,(02)台北市,,(08)高職(高商、高工),,...,快樂,1.0,76.0,獨立,答錯,答對,63.0,60-69歲,4.909428,符合
2,1040123,2021-06-26 10:41:56,2021-06-29 17:20:32,283115.0,男,58.0,(02)台北市,,(21)博士,,...,普通,非常冰冷,90.0,獨立,答對,答對,52.0,50-59歲,0.450735,符合
3,1040131,2021-07-19 10:15:01,2021-07-19 10:32:31,1050.0,女,73.0,(03)新北市,,(20)碩士,,...,普通,50.0,35.0,維持現狀,答對,答對,37.0,30-39歲,0.225117,符合
4,1040139,2021-06-27 10:30:00,2021-06-27 10:39:36,575.0,男,86.0,(02)台北市,,(20)碩士,,...,普通,2.0,70.0,獨立,答對,答對,24.0,18-29歲,0.372256,符合

In [6]:
df.columns.to_list()

['id',
 'startdate',
 'enddate',
 'duration_in_seconds',
 'q1',
 'q2',
 'q3',
 'q3_other',
 'q4',
 'q4_88_text',
 'q5_1',
 'q6_h',
 'q6_m',
 'q7_h',
 'q7_m',
 'q8_1',
 'q8_2',
 'q8_3',
 'q8_4',
 'q8_5',
 'q8_6',
 'q8_88',
 'q8_88_text',
 'q8_90',
 'q9_1',
 'q9_2',
 'q9_3',
 'q9_4',
 'q9_5',
 'q9_6',
 'q9_7',
 'q9_8',
 'q9_88',
 'q9_88_text',
 'q9_90',
 'q10_1',
 'q10_2',
 'q10_3',
 'q10_4',
 'q10_5',
 'q10_6',
 'q10_7',
 'q10_8',
 'q10_9',
 'q10_10',
 'q10_88',
 'q10_88_text',
 'q10_90',
 'q11_1',
 'q11_2',
 'q11_3',
 'q11_4',
 'q11_5',
 'q11_6',
 'q11_7',
 'q11_8',
 'q11_88',
 'q11_88_text',
 'q11_90',
 'q12_1',
 'q12_2',
 'q12_3',
 'q12_4',
 'q12_5',
 'q12_6',
 'q12_7',
 'q12_8',
 'q12_8_text',
 'q12_9',
 'q13_01_1',
 'q13_02_1',
 'q13_02_2',
 'q13_02_3',
 'q13_02_4',
 'q13_02_5',
 'q13_02_6',
 'q13_02_7',
 'q13_02_8',
 'q13_02_8_text',
 'q13_02_9',
 'q13_02_10',
 'q13_03_1',
 'q13_03_2',
 'q13_03_3',
 'q13_03_4',
 'q13_03_5',
 'q13_03_5_text',
 'q13_03_6',
 'q13_03_7',
 'q13_04_1',
 'q13_04_2',
 'q13_04_3',
 'q13_04_4',
 'q13_04_5',
 'q13_04_6',
 'q13_04_7',
 'q13_04_8',
 'q13_04_8_text',
 'q13_04_9',
 'q13_04_10',
 'q13_05_1',
 'q13_05_2',
 'q13_05_3',
 'q13_05_4',
 'q13_05_5',
 'q13_05_5_text',
 'q13_05_6',
 'q13_05_7',
 'q14_01_1',
 'q14_01_2',
 'q14_01_3',
 'q14_01_4',
 'q14_01_5',
 'q14_01_5_text',
 'q14_02_1',
 'q14_02_2',
 'q14_02_3',
 'q14_02_4',
 'q14_02_5',
 'q14_02_5_text',
 'q14_03_1',
 'q14_03_2',
 'q14_03_3',
 'q14_03_4',
 'q14_03_4_text',
 'q15_01',
 'q15_02_1',
 'q15_02_2',
 'q15_02_3',
 'q15_02_4',
 'q15_02_5',
 'q15_02_6',
 'q15_02_7',
 'q15_02_8',
 'q15_02_9',
 'q15_02_10',
 'q15_02_11',
 'q15_02_12',
 'q15_02_13',
 'q15_02_13_text',
 'q15_03_1',
 'q16',
 'q17_01',
 'q17_02',
 'q18',
 'q19_01',
 'q19_02',
 'q20_01_1',
 'q20_02_1',
 'q21a_1',
 'q21a_2',
 'q21a_3',
 'q21a_4',
 'q21a_5',
 'q21a_6',
 'q21a_6_text',
 'q22_01_1',
 'q22_02_1',
 'q22_03_1',
 'q22_04_1',
 'q22_05_1',
 'q23_01_1',
 'q23_02_1',
 'q23_03_1',
 'q23_04_1',
 'q23_05_1',
 'q24_01_1',
 'q24_02_1',
 'q24_03_1',
 'q24_04_1',
 'q24_05_1',
 'q25_01_1',
 'q25_02_1',
 'q25_03_1',
 'q25_04_1',
 'q26_01_1',
 'q26_02_1',
 'q26_03_1',
 'q27_1',
 'q28_1',
 'q28_2',
 'q28_3',
 'q28_4',
 'q28_4_text',
 'q28_5',
 'q29_1',
 'q29_2',
 'q29_3',
 'q29_4',
 'q29_5',
 'q29_5_text',
 'q30_1',
 'q31_1',
 'q32_1',
 'q33_1',
 'q34_1',
 'q35_1',
 'q36_1',
 'q37a',
 'q38_01_1',
 'q38_02_1',
 'q39_1',
 'q40_1',
 'q41_1',
 'q42_1',
 'rq21a',
 'rq37a',
 'qrq2',
 'rrq2',
 'weight',
 'r']

In [5]:
df.iloc[0,:].tolist()

['1030252',
 Timestamp('2021-06-23 23:48:22'),
 Timestamp('2021-06-24 00:13:26'),
 1503.0,
 '女',
 54.0,
 '(02)台北市',
 '',
 '(20)碩士',
 '',
 7.0,
 '1',
 '0',
 '4',
 '0',
 '(01)維繫友誼與他人保持聯絡(傳LINE、滑臉書等)',
 '(02)娛樂消遣(玩遊戲、看卡通動漫、看電影、戲劇、看直播、聽音樂、交友軟體、追星、命理占卜、打發時間、無聊)',
 '(03)獲得時事/新聞/政府資訊(搜尋關鍵字、看新聞、看政府資訊、天氣資訊)',
 '(04)獲得生活休閒資訊(美食、觀光旅遊、醫療衛生保健、家庭生活、親子婚姻關係、交通資訊)',
 '(05)理財消費購物(看理財資訊、網路購物、理財管理、繳費、財經股市)',
 '(06)學習或工作(有支薪)(語言學習、線上課程、使用文書處理軟體、學習各種軟體)',
 nan,
 '',
 nan,
 '(01)LINE',
 '(02)Facebook Messenger(臉書聊天室)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 '(01)臉書(Facebook)',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 '(01)YouTube',
 nan,
 '(03)Netflix 網飛',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 '網路新聞(例如：聯合新聞網、ETtoday東森新聞雲、手機新聞app等)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 '有時',
 '(01)鼓勵言論(例如：台灣加油)',
 '(02)支援言論(例如：購買商品讓店家存活)',
 '(03)幽默言論(例如：苦中作樂化解焦慮)',
 nan,
 nan,
 '(06)科普言論(例如：以民眾能懂的方式解釋疫苗功能)',
 '(07)有資訊性的言論',
 '(08)其他',
 '批評政府',
 nan,
 nan,
 '(01)知道如何防疫',
 '(02)瞭解疫情',
 nan,
 '(04)知道別人在想甚麼',
 nan,
 '',
 nan,
 nan,
 '(01)情緒謾罵',
 nan,
 '(03)惡搞言論(例如：嘲笑、諷刺、酸言酸語)',
 nan,
 nan,
 '(06)不科學言論(例如：推薦偏方對抗新冠肺炎)',
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 nan,
 '(03)讓您心情煩亂',
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 nan,
 '',
 '有',
 nan,
 '透過訂閱制串流服務追劇或看電影(例如：Netflix等)',
 nan,
 '使用即時通訊軟體(例如：LINE、FB 聊天室等)',
 nan,
 nan,
 '看YouTube(例如：網紅影片、遊戲影片、搞笑影片、MV等)',
 nan,
 nan,
 nan,
 nan,
 nan,
 '其他',
 '參加線上運動課程',
 '不滿意',
 '否(跳答至18題)',
 nan,
 nan,
 '否(跳答至20(01)題)',
 nan,
 nan,
 '不可以接受',
 '不可以接受',
 nan,
 nan,
 nan,
 nan,
 nan,
 '其他',
 '已讀',
 '很少',
 '很少',
 '很少',
 '很少',
 '很少',
 '從來沒有',
 '從來沒有',
 '從來沒有',
 '從來沒有',
 '從來沒有',
 '很少',
 '經常',
 '很少',
 '有時',
 '有時',
 '不可以接受',
 '不可以接受',
 '不可以接受',
 '不可以接受',
 '有時',
 '有時',
 '很少',
 '普通',
 nan,
 nan,
 nan,
 nan,
 '',
 '(05)沒有做過上述的抵制行為(跳答至37a題 )',
 nan,
 nan,
 nan,
 nan,
 nan,
 '',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '(5)7個',
 '滿意',
 '普通',
 '快樂',
 65.0,
 65.0,
 '維持現狀',
 '答對',
 '答對',
 56.0,
 '50-59歲',
 0.3490058059293932,
 '符合']